language: node_js
node_js:
- 10
dist: trusty
sudo: required
addons:
  chrome: stable
before_script:
- npm run test:lint:js
- npm run test:lint:wc
script:
- set -e
- polymer test --skip-plugin sauce
- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then polymer test --skip-plugin local; fi'
- if [ "$TRAVIS_BRANCH" == "master" ]; then frauci-update-version; fi
env:
  global:
  - REPO_NAME=d2l-upcoming-assessments-ui
  #SAUCE_USERNAME
  - secure: 4SVWT6CBeSkKYxNo6AczT/McoF7DpG/YGdHtUSKcNeWoOnQRyyyLd70XWKoiy3pV99MWyMm2Q0SSk7SVtfL32EUW4yoVTmo18+KFYGu/JuuuLMk8omshe/cfIKiLFXK+kc+B3+VqQdF1mA3lhmQtBsJXqQzuqiey5RucRzlp/FgHS3b/AmXvVhPLUWXfFx+VkyUbJuOw6YRYr3VqW2T8KU4iCcMXoDFxky2mETJxFt6DieVmEKvWqAlfcwgeeodZI3D76QaFTzddS1NQMlhGydUcl57uu+zfUw74quIK/3tfBp9aioIENR094iZMLJY9/B9mnG5XVexGGXgSgcWbMMykRkS5PN8YWBGJSVqWqwDxj8Z7rPkVPGWfvc9FxkVpKcFj2ZTChb+L+KyHjGl6GaPs0rLW4K1clFrNFxkLbp83LC9hzVKHSPJORlSUYLdkR5m1hw9XKP7Aj/YDnYe6wfhHxOeVbA7VM6Ns4OboY08KzeKKGaH/UByRoreiOJhW+7IgedfwQjpEilzgzRsYZ8XmxdTAEQTaVv6Z6OmghrMUQflLzUJwp8KBq1UN/pTao4QsAaCLGn74e5xHwzmnWAdPa62EQQRjE+7YgPgT9He++EDqXjS64j1SJvQeFiWUv/LfbzBc5GwNUzTH8Cdb0XpejHWeKrCw1Dm0pqXwj8I=
  #SAUCE_ACCESS_KEY
  - secure: zUID1VHKhJymz+JIyn3DaxTKiS/NaSxByUB/gbVkEQ/7VGvi9kbmJYnq3FmtCj734auLcp5KUFLUZfN2UM5GhzSzJ3hc5DRVcvGw/wWA1UX01DYrojdw/V5DQREW+v1VoG6GBme8PdHCUUE+0OzxViQsZ4y90CanS4A8T/LjLl35i0Vuq2ZKvewdzBJrk4o6e5p2+B/82//iGhIZUiPvNfEPO2c7wsZ+WiyzyQQgtOL0/MJ7EV0h+KepXpcnA84AdOZAIKdeqOfEzXVbBorFl678JGzFiHsLUSB/zKADgiRPLDPOfhpbOxf7bp6S18fjyeLeDGpEBWvfVdkm9q0eHQKJNEr1bCPBDmS+Va86yqkpXgDkSFRyyk0dErj9Fx6q/0LcGPr8WlH9M/FRDDwBUgKqs/g8BzMihlqcRDWVyt6rlEfW7Udag96iP+zYmzRk8rpaEb8FF1gBJ1oxQA4Urr9jSAHUr1qUPwj2ZBlZb+G76svS1ZA2/3LjsfqfcNWSIJA3R4sNTH2OSVZjicAItLX1JWnYFSBNT9aG+w2RR1s9xf+H9b7lUT3mSdVacQ4GcYfX1hQrN9e2jtAisPFYd2aL6qjnXSrcAHtAuN7zUzcEW0DfhrKpiLpYwbpKnToemRS4C57djPGDh00Ylb7iGjQHu9CLADtFdK13N2N9SBo=
  #GITHUB_RELEASE_TOKEN
  - secure: FtoFWKq4wO/I3lTnzAnMSEQ3pn3/clOuQr4d7Qpli3tkHgMqbWDOFOL4+uD7Nlc+Oza+qWWzl+w2gOz+7QCRb1YJl1TgO2DjNEsSGIeGgs1+kbI3lb2fq2KWCK+VFBrWyAsOZ5e1ppYOA7coVoDppLdLswLqESyRB1+tT2AxLYcy21TbHC2JrNCPqFatgzqovf0rJoD6vCKPdYOoQpVcLbGM0DXTeIFslON107w7j2WkYPtZcq/TINNQD2hIAoKzvM2/fzI85oFzO4chIbUvl7p2Wf5TWHCYd8FWyv45xc7tBUH4AXYae6LD/+X8JlTrmYtdoRbt6tcbnHSAswAkq2iL/PG41hWnZ/D8w5An48qvvFgO5/dfnTqcZ9hDw7ExaxV2UvWWC0vK31Trvc724sRhEEV3Mlbpcop+t0QbGpFfnVhG+P6ZMFbyyM7UVxqAKQI1oR1nPfXhOtOVsyRPRkd2n4Ht8BZY6bIZdr74x1baxyvJzauMycg0oic1y6hth3iRkf1eaVPh/OZuSd1BHFOsZqe/cmOLFfDcA/tz+ECr5jeXcM00qhGHwsSkVLMgKNKr+yH1pC40Bgvk73hMwMhmCzXFuo2ernzHlBfIloZTqeSmYvteDqdGFUKQKKSUEpUedWzFxUSRWVxO4/9PcsyPktdLDUC/x/QkOIBM+h0=
